services:
  - type: web
    name: brain-mri-analyzer
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: ONNX_MODEL_PATH
        value: /app/checkpoints/model.onnx
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://brain-mri-analyzer.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
